/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JOptionPane;
import Modelo.*;
import java.awt.event.KeyEvent;

/**
 *
 * @author Home
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtext_ingresarPolinomio = new javax.swing.JTextField();
        jButton_agregarPolinomio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox_seleccionarPolinomio = new javax.swing.JComboBox<String>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_resultado = new javax.swing.JTextArea();
        jButton_evaluar = new javax.swing.JButton();
        jTextField_evaluar = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jButton_agregar_resultado = new javax.swing.JButton();
        jButton_eliminar_Polinomio = new javax.swing.JButton();
        jTextField_eliminar_polinomio = new javax.swing.JTextField();
        jButton_Eliminar = new javax.swing.JButton();
        jButton_derivada_n = new javax.swing.JButton();
        jTextField_derivada_n = new javax.swing.JTextField();
        jButton_derivada = new javax.swing.JButton();
        jButton_integral_definida = new javax.swing.JButton();
        jButton_antiderivada = new javax.swing.JButton();
        jTextField_intervaloInicial = new javax.swing.JTextField();
        jTextField_intervaloFinal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox_seleccionarSegundoPolinomio = new javax.swing.JComboBox<String>();
        jButton_sumar = new javax.swing.JButton();
        jButton_multiplicar = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jButton_factor = new javax.swing.JButton();
        jTextField_factor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Polinomios");
        setBackground(new java.awt.Color(102, 153, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(740, 535));
        setResizable(false);
        getContentPane().setLayout(null);

        jtext_ingresarPolinomio.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        getContentPane().add(jtext_ingresarPolinomio);
        jtext_ingresarPolinomio.setBounds(161, 25, 441, 19);

        jButton_agregarPolinomio.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton_agregarPolinomio.setText("Agregar");
        jButton_agregarPolinomio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_agregarPolinomioActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_agregarPolinomio);
        jButton_agregarPolinomio.setBounds(608, 24, 90, 21);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel1.setText("Ingresar Polinomio:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(22, 28, 99, 13);

        jComboBox_seleccionarPolinomio.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        getContentPane().add(jComboBox_seleccionarPolinomio);
        jComboBox_seleccionarPolinomio.setBounds(159, 83, 443, 19);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(20, 73, 680, 9);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel2.setText("Seleccionar Polinomio:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 85, 112, 13);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(20, 190, 680, 10);

        jTextArea_resultado.setColumns(20);
        jTextArea_resultado.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTextArea_resultado.setRows(5);
        jTextArea_resultado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextArea_resultadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea_resultado);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 421, 582, 40);

        jButton_evaluar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton_evaluar.setText("Evaluar");
        jButton_evaluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_evaluarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_evaluar);
        jButton_evaluar.setBounds(153, 130, 90, 21);

        jTextField_evaluar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTextField_evaluar.setText("0");
        jTextField_evaluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_evaluarKeyTyped(evt);
            }
        });
        getContentPane().add(jTextField_evaluar);
        jTextField_evaluar.setBounds(153, 159, 90, 19);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(20, 393, 680, 2);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel3.setText("Resultado:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 401, 70, 13);

        jButton_agregar_resultado.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton_agregar_resultado.setText("Agregar");
        jButton_agregar_resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_agregar_resultadoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_agregar_resultado);
        jButton_agregar_resultado.setBounds(608, 421, 100, 21);

        jButton_eliminar_Polinomio.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton_eliminar_Polinomio.setText("Eliminar Monomio");
        jButton_eliminar_Polinomio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_eliminar_PolinomioActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_eliminar_Polinomio);
        jButton_eliminar_Polinomio.setBounds(260, 130, 150, 21);

        jTextField_eliminar_polinomio.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTextField_eliminar_polinomio.setText("x - c");
        getContentPane().add(jTextField_eliminar_polinomio);
        jTextField_eliminar_polinomio.setBounds(260, 160, 150, 19);

        jButton_Eliminar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton_Eliminar.setText("Eliminar");
        jButton_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Eliminar);
        jButton_Eliminar.setBounds(612, 82, 90, 21);

        jButton_derivada_n.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton_derivada_n.setText("Derivada n-sima");
        jButton_derivada_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_derivada_nActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_derivada_n);
        jButton_derivada_n.setBounds(150, 211, 120, 21);

        jTextField_derivada_n.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTextField_derivada_n.setText("0");
        jTextField_derivada_n.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_derivada_nKeyTyped(evt);
            }
        });
        getContentPane().add(jTextField_derivada_n);
        jTextField_derivada_n.setBounds(150, 240, 120, 19);

        jButton_derivada.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton_derivada.setText("Derivada");
        jButton_derivada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_derivadaActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_derivada);
        jButton_derivada.setBounds(280, 210, 90, 21);

        jButton_integral_definida.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton_integral_definida.setText("Integral definida");
        jButton_integral_definida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_integral_definidaActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_integral_definida);
        jButton_integral_definida.setBounds(380, 210, 120, 21);

        jButton_antiderivada.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton_antiderivada.setText("Antiderivada");
        jButton_antiderivada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_antiderivadaActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_antiderivada);
        jButton_antiderivada.setBounds(510, 210, 110, 21);

        jTextField_intervaloInicial.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTextField_intervaloInicial.setText("0");
        jTextField_intervaloInicial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_intervaloInicialKeyTyped(evt);
            }
        });
        getContentPane().add(jTextField_intervaloInicial);
        jTextField_intervaloInicial.setBounds(380, 240, 45, 19);

        jTextField_intervaloFinal.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTextField_intervaloFinal.setText("0");
        jTextField_intervaloFinal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_intervaloFinalKeyTyped(evt);
            }
        });
        getContentPane().add(jTextField_intervaloFinal);
        jTextField_intervaloFinal.setBounds(450, 240, 47, 19);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel4.setText("Seleccionar 2do Polinomio:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(17, 312, 134, 13);

        jComboBox_seleccionarSegundoPolinomio.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        getContentPane().add(jComboBox_seleccionarSegundoPolinomio);
        jComboBox_seleccionarSegundoPolinomio.setBounds(153, 309, 449, 19);

        jButton_sumar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton_sumar.setText("Sumar");
        jButton_sumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_sumarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_sumar);
        jButton_sumar.setBounds(153, 347, 90, 21);

        jButton_multiplicar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton_multiplicar.setText("Multiplicar");
        jButton_multiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_multiplicarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_multiplicar);
        jButton_multiplicar.setBounds(252, 347, 100, 21);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(17, 287, 680, 10);

        jButton_factor.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton_factor.setText("Factor");
        jButton_factor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_factorActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_factor);
        jButton_factor.setBounds(420, 130, 90, 21);

        jTextField_factor.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTextField_factor.setText("x - c");
        getContentPane().add(jTextField_factor);
        jTextField_factor.setBounds(420, 160, 90, 19);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel5.setText("Ej: 8x3 + 2x2 - 5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(160, 50, 200, 13);

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabel6.setText("Nota: Algunas operaciones con decimales pueden verse afectadas minimamente por la falta de precisión de la clase Double de Java. ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 470, 670, 13);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_evaluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_evaluarActionPerformed
        if(jComboBox_seleccionarPolinomio.getItemCount()==0){
            JOptionPane.showMessageDialog(null, "Debes agregar un polinomio primero");
            return;
        }
        String texto = jComboBox_seleccionarPolinomio.getSelectedItem().toString();        
        Double valor = Double.parseDouble(jTextField_evaluar.getText());
        Polinomio polinomio = new Polinomio(texto);
        Double resultado = polinomio.evaluarPolinomio(valor);
        jTextArea_resultado.setText(resultado.toString());
    }//GEN-LAST:event_jButton_evaluarActionPerformed

    private void jButton_agregarPolinomioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_agregarPolinomioActionPerformed
        String texto = jtext_ingresarPolinomio.getText();
        if(texto.equalsIgnoreCase("")){
        JOptionPane.showMessageDialog(null, "El campo 'Ingresar Polinomio' está vacío");
        return;
    }
        jComboBox_seleccionarPolinomio.addItem(texto);
        jComboBox_seleccionarSegundoPolinomio.addItem(texto);
        jtext_ingresarPolinomio.setText("");
        
    }//GEN-LAST:event_jButton_agregarPolinomioActionPerformed

    private void jButton_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EliminarActionPerformed
        jComboBox_seleccionarSegundoPolinomio.removeItem(jComboBox_seleccionarPolinomio.getSelectedItem());
        jComboBox_seleccionarPolinomio.removeItem(jComboBox_seleccionarPolinomio.getSelectedItem());        
       
    }//GEN-LAST:event_jButton_EliminarActionPerformed

    private void jTextField_evaluarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_evaluarKeyTyped
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)  & c!='.'){
            if((c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE)){
                return;
            }
            evt.consume();
            JOptionPane.showMessageDialog(null, "El campo sólo pude contener números enteros o decimales");
            
        }
        if(c=='.'& jTextField_evaluar.getText().contains(".")){
            evt.consume();
            JOptionPane.showMessageDialog(null, "El campo sólo pude contener números enteros o decimales");
            
        }        
    }//GEN-LAST:event_jTextField_evaluarKeyTyped

    private void jTextField_derivada_nKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_derivada_nKeyTyped
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
            if((c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE)){
                return;
            }
            evt.consume();
            JOptionPane.showMessageDialog(null, "El campo sólo pude contener números enteros");
            
        }
    }//GEN-LAST:event_jTextField_derivada_nKeyTyped

    private void jTextField_intervaloInicialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_intervaloInicialKeyTyped
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
            if((c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE)){
                return;
            }
            evt.consume();
            JOptionPane.showMessageDialog(null, "El campo sólo pude contener números enteros");
            
        }
    }//GEN-LAST:event_jTextField_intervaloInicialKeyTyped

    private void jTextField_intervaloFinalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_intervaloFinalKeyTyped
     char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
            if((c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE)){
                return;
            }
            evt.consume();
            JOptionPane.showMessageDialog(null, "El campo sólo pude contener números enteros");
            
        }
    }//GEN-LAST:event_jTextField_intervaloFinalKeyTyped

    private void jButton_eliminar_PolinomioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_eliminar_PolinomioActionPerformed
        if(jComboBox_seleccionarPolinomio.getItemCount()==0){
            JOptionPane.showMessageDialog(null, "Debes agregar un polinomio primero");
            return;
        }
        Polinomio polinomio = new Polinomio(jComboBox_seleccionarPolinomio.getSelectedItem().toString());
        Polinomio monomio = new Polinomio(jTextField_eliminar_polinomio.getText());
        polinomio.eliminarMonomio(monomio);
        jTextArea_resultado.setText(polinomio.imprimirPolinomio());
        
        
    }//GEN-LAST:event_jButton_eliminar_PolinomioActionPerformed

    private void jTextArea_resultadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextArea_resultadoMouseClicked
       this.jTextArea_resultado.setEditable(false);
    }//GEN-LAST:event_jTextArea_resultadoMouseClicked

    private void jButton_factorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_factorActionPerformed
       if(jComboBox_seleccionarPolinomio.getItemCount()==0){
            JOptionPane.showMessageDialog(null, "Debes agregar un polinomio primero");
            return;
        }
       Polinomio polinomio = new Polinomio(jComboBox_seleccionarPolinomio.getSelectedItem().toString());
       Polinomio factor = new Polinomio(jTextField_factor.getText());
       String mensaje = "";
       if(polinomio.factorPolinomio(factor)==true){
           mensaje = "El "+polinomio.imprimirPolinomio()+ " es factorizable con "+factor.imprimirPolinomio();
       }
       else{
           mensaje = "El "+polinomio.imprimirPolinomio()+ " no es factorizable con "+factor.imprimirPolinomio();
       }        
       JOptionPane.showMessageDialog(null, mensaje);
    }//GEN-LAST:event_jButton_factorActionPerformed

    private void jButton_derivada_nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_derivada_nActionPerformed
        if(jComboBox_seleccionarPolinomio.getItemCount()==0){
            JOptionPane.showMessageDialog(null, "Debes agregar un polinomio primero");
            return;
        }
        Polinomio polinomio = new Polinomio(jComboBox_seleccionarPolinomio.getSelectedItem().toString());
        int valor = Integer.parseInt(jTextField_derivada_n.getText());
        Polinomio resultado = polinomio.enesimaDerivada(valor);
        jTextArea_resultado.setText(resultado.imprimirPolinomio());
    }//GEN-LAST:event_jButton_derivada_nActionPerformed

    private void jButton_derivadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_derivadaActionPerformed
        if(jComboBox_seleccionarPolinomio.getItemCount()==0){
            JOptionPane.showMessageDialog(null, "Debes agregar un polinomio primero");
            return;
        }
        Polinomio polinomio = new Polinomio(jComboBox_seleccionarPolinomio.getSelectedItem().toString());        
        Polinomio resultado = polinomio.primeraDerivada();
        String derivada = resultado.imprimirPolinomio();
        if(derivada.equalsIgnoreCase("")){
            derivada = "0";
        }
        jTextArea_resultado.setText(derivada);
    }//GEN-LAST:event_jButton_derivadaActionPerformed

    private void jButton_antiderivadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_antiderivadaActionPerformed
        if(jComboBox_seleccionarPolinomio.getItemCount()==0){
            JOptionPane.showMessageDialog(null, "Debes agregar un polinomio primero");
            return;
        }
        Polinomio polinomio = new Polinomio(jComboBox_seleccionarPolinomio.getSelectedItem().toString());        
        Polinomio resultado = polinomio.integralIndefinida();
        if(resultado == null){
            JOptionPane.showMessageDialog(null, "La integral del monomio (x-1) no está definida");
            return;
        }
        jTextArea_resultado.setText(resultado.imprimirPolinomio());
    }//GEN-LAST:event_jButton_antiderivadaActionPerformed

    private void jButton_integral_definidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_integral_definidaActionPerformed
        if(jComboBox_seleccionarPolinomio.getItemCount()==0){
            JOptionPane.showMessageDialog(null, "Debes agregar un polinomio primero");
            return;
        }
        Polinomio polinomio = new Polinomio(jComboBox_seleccionarPolinomio.getSelectedItem().toString());
        Double Iinicio = Double.parseDouble(jTextField_intervaloInicial.getText());
        Double Ifinal = Double.parseDouble(jTextField_intervaloFinal.getText());
        Double resultado = polinomio.integralDefinifa(Iinicio, Ifinal);
        jTextArea_resultado.setText(resultado.toString());
    }//GEN-LAST:event_jButton_integral_definidaActionPerformed

    private void jButton_sumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_sumarActionPerformed
       if(jComboBox_seleccionarPolinomio.getItemCount()==0){
            JOptionPane.showMessageDialog(null, "Debes agregar un polinomio primero");
            return;
        }
       Polinomio polinomio1 = new Polinomio(jComboBox_seleccionarPolinomio.getSelectedItem().toString());
       Polinomio polinomio2 = new Polinomio(jComboBox_seleccionarSegundoPolinomio.getSelectedItem().toString());
       Polinomio resultado = polinomio1.sumarPolinomios(polinomio2);
       jTextArea_resultado.setText(resultado.imprimirPolinomio());
    }//GEN-LAST:event_jButton_sumarActionPerformed

    private void jButton_multiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_multiplicarActionPerformed
       if(jComboBox_seleccionarPolinomio.getItemCount()==0){
            JOptionPane.showMessageDialog(null, "Debes agregar un polinomio primero");
            return;
        }
       Polinomio polinomio1 = new Polinomio(jComboBox_seleccionarPolinomio.getSelectedItem().toString());
       Polinomio polinomio2 = new Polinomio(jComboBox_seleccionarSegundoPolinomio.getSelectedItem().toString());
       Polinomio resultado = polinomio1.MultiplicarPolinomios(polinomio2);
       jTextArea_resultado.setText(resultado.imprimirPolinomio());
    }//GEN-LAST:event_jButton_multiplicarActionPerformed

    private void jButton_agregar_resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_agregar_resultadoActionPerformed
        String polinomio = this.jTextArea_resultado.getText();
        if(polinomio.equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null, "El campo 'Resultado' está vacío");
            return;
           
        }
        this.jComboBox_seleccionarPolinomio.addItem(polinomio);
        this.jComboBox_seleccionarSegundoPolinomio.addItem(polinomio);
        
    }//GEN-LAST:event_jButton_agregar_resultadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Eliminar;
    private javax.swing.JButton jButton_agregarPolinomio;
    private javax.swing.JButton jButton_agregar_resultado;
    private javax.swing.JButton jButton_antiderivada;
    private javax.swing.JButton jButton_derivada;
    private javax.swing.JButton jButton_derivada_n;
    private javax.swing.JButton jButton_eliminar_Polinomio;
    private javax.swing.JButton jButton_evaluar;
    private javax.swing.JButton jButton_factor;
    private javax.swing.JButton jButton_integral_definida;
    private javax.swing.JButton jButton_multiplicar;
    private javax.swing.JButton jButton_sumar;
    private javax.swing.JComboBox<String> jComboBox_seleccionarPolinomio;
    private javax.swing.JComboBox<String> jComboBox_seleccionarSegundoPolinomio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextArea jTextArea_resultado;
    private javax.swing.JTextField jTextField_derivada_n;
    private javax.swing.JTextField jTextField_eliminar_polinomio;
    private javax.swing.JTextField jTextField_evaluar;
    private javax.swing.JTextField jTextField_factor;
    private javax.swing.JTextField jTextField_intervaloFinal;
    private javax.swing.JTextField jTextField_intervaloInicial;
    private javax.swing.JTextField jtext_ingresarPolinomio;
    // End of variables declaration//GEN-END:variables
}
